[project]
name = "robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catkin-pkg>=1.0.0",
    "pynput>=1.7.7",
    "pytest>=8.3.4",
]
